version: "3.3"
services:
  node_backend:
    container_name: node_server
    image: f883189fb10f28b00af8394bd7c18d98822073a54e2ce0db21f28bc8944cc9ea
    restart: always
    ports:
      - 80:80
    command: npm run dev
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:14"
    ports:
      - 5434:5434
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
volumes:
  nps_data: {}
