version: "3.3"
services:
  node_backend:
    container_name: node_server
    image: kondrashev/articles:latest
    restart: always
    ports:
      - 80:80
    environment:
      - DB_NAME=articles
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=node_db
    command: npm run dev
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:14"
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=articles
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
volumes:
  nps_data: {}
