version: "3.8"
services:
  node_backend:
    container_name: node_server
    image: node_server:0.0.1
    build:
      context: .
    restart: always
    ports:
      - 80:80
    environment:
      - PORT=80
      - DB_NAME=articles
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=node_db
    command: npm run dev
    depends_on:
      - node_db
    volumes:
      - /Users/pavel/Documents/Development/Front-End/tests/articles:/app
      - /app/node_modules
  node_db:
    container_name: node_db
    image: "postgres:14"
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=articles
    volumes:
      - /var/lib/postgresql/data:/nps_data
    restart: always
