version: "3.3"
services:
  node_backend:
    container_name: node_server
    image: articles
    build:
      context: .
    restart: always
    ports:
      - 80:80
    command: npm run dev
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:14"
    ports:
      - 5434:5434
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
volumes:
  nps_data: {}
