version: "3.3"
services:
  node_db:
    container_name: node_db
    image: "postgres:14"
    ports:
      - 5434:5434
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
  node_backend:
    build: .
    container_name: node_server
    restart: always
    ports:
      - 80:80
    command: npm run dev
    depends_on:
      - node_db
    volumes:
      - /Users/pavel/Documents/Development/Front-End/tests/articles:/app
      - /app/node_modules
volumes:
  nps_data: {}
